[ docs ] deploy.yml 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -47,17 +47,23 @@ jobs:
         shell: bash
 
       - name: Build with Gradle
-        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
-#        run: ./gradlew build
+#        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
+        run: |
+          ./gradlew --version
+          ./gradlew build
 #        shell: bash
-        with:
-          arguments: clean build -x test
+#        with:
+#          arguments: clean build -x test
 
       - name: Make Zip file
-        run: zip -qq -r ./$GITHUB_SHA.zip .
-        shell: bash
+#        run: zip -qq -r ./$GITHUB_SHA.zip .
+#        shell: bash
+        run: |
+          mv ./build/libs/simya-0.0.1-SNAPSHOT.jar ./
+          zip buildFile.zip ./scripts/deploy.sh  ./scripts/server-check.sh ./appspec.yml ./simya-0.0.1-SNAPSHOT.jar 
 
-          
+      
+
       # 4. AWS 인증(IAM 사용자 Access Key, Secret Key 활용)
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
@@ -69,11 +75,14 @@ jobs:
       # 5. 빌드 결과물을 S3 버킷에 업로드
       - name: Upload to AWS S3
         run: | 
-          aws deploy push \
-            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
-            --ignore-hidden-files \
-            --s3-location s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip \
-            --source .
+          aws s3 cp \
+            --region ap-northeast-2 \
+            buildFile.zip s3://${{ env.S3_BUCKET_NAME }}/community-build/
+#          aws deploy push \
+#            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
+#            --ignore-hidden-files \
+#            --s3-location s3://${{ env.S3_BUCKET_NAME }}/$GITHUB_SHA.zip \
+#            --source .
             
       # 6. S3 버킷에 있는 파일을 대상으로 CodeDeploy 실행
       - name: Deploy to AWS EC2 from S3
@@ -82,4 +91,21 @@ jobs:
           --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
           --deployment-config-name CodeDeployDefault.AllAtOnce \
           --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
-          --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip
+          --s3-location bucket=${{ env.S3_BUCKET_NAME }},key=community-build/buildFile.zip,bundleType=zip > deploymentId.txt
+          
+          DEPLOYMENT_ID=$(cat deploymentId.txt | jq -r '.deploymentId')
+
+          echo "Wait 60 seconds for deployment and test"
+          sleep 60
+
+          IS_SUCCESS=$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID | jq -r '.deploymentInfo.status')
+
+          echo $IS_SUCCESS;
+
+          if [ "$IS_SUCCESS" = "Succeeded" ];
+          then
+            echo "SUCCESS DEPLOY!"
+          else
+            echo "FAIL DEPLOY!"
+            exit 1
+          fi
